events {
    worker_connections 1024;
}

http {
    upstream auth_service {
        server ticket-system-distributed-auth-service-1:3000;
    }

    upstream event_service {
        server ticket-system-distributed-event-service-1:3000;
        server ticket-system-distributed-event-service-2:3000;
    }

    upstream order_service {
        server ticket-system-distributed-order-service-1:3000;
        server ticket-system-distributed-order-service-2:3000;
    }

    upstream payment_service {
        server ticket-system-distributed-payment-service-1:3000;
    }

    upstream notification_service {
        server ticket-system-distributed-notification-service-1:3000;
    }

    server {
        listen 80;

        location /api/auth {
            rewrite ^/api/auth(.*)$ /auth$1 break;
            proxy_pass http://auth_service;
        }

        location /api/events {
            rewrite ^/api/events(.*)$ /events$1 break;
            proxy_pass http://event_service;
        }

        location /api/orders {
            rewrite ^/api/orders(.*)$ /orders$1 break;
            proxy_pass http://order_service;
        }

        location /api/payments {
            rewrite ^/api/payments(.*)$ /payments$1 break;
            proxy_pass http://payment_service;
        }

        location /health {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }
}